apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - kiali-ns.yaml


helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: kiali-operator
    releaseName: kiali-operator
    valuesFile: kiali-values.yaml
    namespace: kiali-operator
    includeCRDs: true
