auth:
  existingSecret: postgres-secrets
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

fullnameOverride: postgres

primary:
  persistence:
    enabled: false
    size: 2Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 40m
    limits:
      memory: 1Gi
      cpu: 1000m

service:
  type: ClusterIP
  port: 5432

architecture: standalone
