# Strategic merge patch for core-voki-creation-service in production
# Uncomment / adjust as needed
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-voki-creation-service
spec:
  template:
    spec:
      containers:
        - name: core-voki-creation-service
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "500m"
