apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: istiod
    releaseName: istiod
    valuesFile: istiod-values.yaml
    namespace: istio-system